### ISSUE TITLE
An IntegrityError occurred: duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by fcorreiadafonseca** [DTOcean/dtocean#24] opened 2018-08-20 17:34 UTC
Hello everyone,
I have been trying to get the DTOcean tool to work. First I couldn't install DTOcean since I was getting the error related with the installation directory when installing the Hydrodynamics package. 

Once having introduced the directory in the regedit, I managed to install the tool and run it. However, whenever I press the initiate dataflow icon and pressing ok after the "PASSED" prompt message, the progress bar starts to load but stays loading indefinitely.

I did not have a python installation prior to installing DTOcean. I have succesfully installled the database by following the tutorial (pgadmin III). However, I am stuck on this point. 

Any thoughts?
Thank you in advance,
Francisco

**Comment by H0R5E** [comment] 2018-08-22 10:53
Hi Francisco,

Which simulation are you trying to run? How long were you waiting?

You can find log files in the "YourUserDirectory\AppData\Roaming\DTOcean\dtocean_app\logs" folder. The latest one should be called dtocean_app.log. Is there any relevant information towards the end of that file?

**Comment by fcorreiadafonseca** [comment] 2018-08-22 14:27
Hello @H0R5E,
Thank you for your fast reply.
I was following the available tutorials (Tutorial 1 #&#xfeff;3 Input preparation) for the simple example with Hydro+Electrical. I don't seem to have the "dtocean_app" folder in the "YourUserDirectory\AppData\Roaming\DTOcean\" directory, so I couldn't find the log files.

Anyway, I have let the progress bar load for roughly 30 minutes and ended up getting the following error:
![dtocean_snap](https://user-images.githubusercontent.com/42550551/44469450-6c8a4c80-a61f-11e8-8315-54bc00a67f4a.PNG)
Not sure of what might be happening.
Thank you in advance!
Francisco

**Comment by H0R5E** [comment] 2018-08-22 14:50
Sorry, the folder will be "dtocean_gui" on the version you are running.

Looks like some sort of database corruption caused by a duplicate key. Which version of postgreSQL are you using? DTOcean was only tested on 9.3 and 9.4. Did you change any data in the database? Could you have restored it twice?

In general, there are lots of problems with the release you are trying to use. Some of those problems are resolved in the latest anaconda version (1.0.3) -> see [here](https://github.com/DTOcean/dtocean-app#anaconda-package) for instructions <- which I recommend you upgrade to if you want to continue. There will also be a new major release (including an installer) before the end of the year, which will be much more stable, so you might want to wait for that.

I've not seen this issue before, so if you want to continue investigating I would be interested to know why it's happening.

**Comment by H0R5E** [comment] 2018-08-22 15:07
Francisco, do you get this issue when you select a device before initiating the dataflow? I notice the device isn't set on the screenshot you added.

**Comment by fcorreiadafonseca** [comment] 2018-08-23 15:45
Hello @H0R5E ,
I am running postgreSQL version 9.3.23. It doesn't change anything if I select the device but I might have restored the database twice, now that you mention it. How can I see if that is indeed the problem? I will try to look into it, thanks.
Francisco

**Comment by H0R5E** [comment] 2018-08-23 19:03
Hi Francisco, you should try deleting the database and then recreating it from scratch. This is the only way to start afresh.

**Comment by fcorreiadafonseca** [comment] 2018-08-24 07:36
Hello @H0R5E, thank you for the tip. Everything seems to be working now! I will look into the next anaconda version as well.
Thanks!
Francisco

**Comment by H0R5E** [comment] 2018-08-24 14:37
Hi Francisco, glad you have it sorted and thanks for your feedback.

As I said, there are still a number of problems, even with version 1.0.3, which will be fixed in the next update.

**Closed as completed by H0R5E** 2018-08-24 14:37 UTC
Labels: not a bug
